
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Reporteria;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 32;
  public static final int IGUAL = 20;
  public static final int GENERAR_REPORTE_ESTADISTICO = 3;
  public static final int DOLLAR = 9;
  public static final int DECIMAL = 29;
  public static final int GRAFICA_BARRAS = 4;
  public static final int DOS_PUNTOS = 19;
  public static final int GRAFICA_PIE = 5;
  public static final int VALORES = 25;
  public static final int STRING = 21;
  public static final int COMA = 17;
  public static final int COMPARE = 12;
  public static final int EOF = 0;
  public static final int DEFINIR_GLOBALES = 2;
  public static final int GRAFICA_LINEAS = 6;
  public static final int NUMERO = 30;
  public static final int PARENTESIS_C = 14;
  public static final int error = 1;
  public static final int PUNTAJE_ESPECIFICO = 8;
  public static final int IDENTIFICADOR = 31;
  public static final int PARENTESIS_A = 13;
  public static final int LLAVE_C = 11;
  public static final int P_COMA = 18;
  public static final int ARCHIVO = 28;
  public static final int LLAVE_A = 10;
  public static final int EJEX = 24;
  public static final int CUADRADA_C = 16;
  public static final int TITULOY = 27;
  public static final int TITULOX = 26;
  public static final int TITULO = 23;
  public static final int CUADRADA_A = 15;
  public static final int PUNTAJE_GENERAL = 7;
  public static final int DOUBLE = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEFINIR_GLOBALES",
  "GENERAR_REPORTE_ESTADISTICO",
  "GRAFICA_BARRAS",
  "GRAFICA_PIE",
  "GRAFICA_LINEAS",
  "PUNTAJE_GENERAL",
  "PUNTAJE_ESPECIFICO",
  "DOLLAR",
  "LLAVE_A",
  "LLAVE_C",
  "COMPARE",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "CUADRADA_A",
  "CUADRADA_C",
  "COMA",
  "P_COMA",
  "DOS_PUNTOS",
  "IGUAL",
  "STRING",
  "DOUBLE",
  "TITULO",
  "EJEX",
  "VALORES",
  "TITULOX",
  "TITULOY",
  "ARCHIVO",
  "DECIMAL",
  "NUMERO",
  "IDENTIFICADOR",
  "CADENA"
  };
}

