
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package LenguajeCopias;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 32;
  public static final int NUMERO = 14;
  public static final int CONST = 11;
  public static final int CASE = 41;
  public static final int DOS_PUNTOS = 42;
  public static final int LLAVE_C = 6;
  public static final int ASTERISCO = 31;
  public static final int FOR = 37;
  public static final int LLAVE_A = 5;
  public static final int IDENTIFICADOR = 13;
  public static final int NOT = 28;
  public static final int AND = 26;
  public static final int IGUAL = 12;
  public static final int OR = 27;
  public static final int CLASS = 2;
  public static final int IF = 18;
  public static final int EOF = 0;
  public static final int TRUE = 16;
  public static final int error = 1;
  public static final int COMA = 7;
  public static final int CADENA = 15;
  public static final int MODULO = 34;
  public static final int MENOS = 30;
  public static final int MENOR = 22;
  public static final int REQUIRE = 46;
  public static final int BREAK = 43;
  public static final int DESIGUAL = 21;
  public static final int SWITCH = 40;
  public static final int DOBLE_MAS = 35;
  public static final int MAYOR = 24;
  public static final int DOBLE_IGUAL = 20;
  public static final int POTENCIA = 33;
  public static final int ELSE = 19;
  public static final int PARENTESIS_C = 4;
  public static final int WHILE = 39;
  public static final int PARENTESIS_A = 3;
  public static final int DEFAULT = 44;
  public static final int MAYOR_IGUAL = 25;
  public static final int LET = 10;
  public static final int P_COMA = 8;
  public static final int CONSOLELOG = 45;
  public static final int MENOR_IGUAL = 23;
  public static final int FALSE = 17;
  public static final int DOBLE_MENOS = 36;
  public static final int VAR = 9;
  public static final int DO = 38;
  public static final int MAS = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAVE_A",
  "LLAVE_C",
  "COMA",
  "P_COMA",
  "VAR",
  "LET",
  "CONST",
  "IGUAL",
  "IDENTIFICADOR",
  "NUMERO",
  "CADENA",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "DOBLE_IGUAL",
  "DESIGUAL",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "MAS",
  "MENOS",
  "ASTERISCO",
  "DIAGONAL",
  "POTENCIA",
  "MODULO",
  "DOBLE_MAS",
  "DOBLE_MENOS",
  "FOR",
  "DO",
  "WHILE",
  "SWITCH",
  "CASE",
  "DOS_PUNTOS",
  "BREAK",
  "DEFAULT",
  "CONSOLELOG",
  "REQUIRE"
  };
}

